env: "local"
http_server:
  address: "localhost:8082"
  timeout: 4s
sql_config:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "1"
  dbname: "postgres"
steam_api:
  key: "BBF805EFC23EADDF7002101399628FCD"